/**
 * Fictional reference data for the simulated hospital ("HIMS
 * Simulation"). Names, numbers and people are invented.
 */
import type {
  DepartmentKind,
  Frequency,
  LabParameter,
  MedicineForm,
  Route,
  SampleType,
  StaffRole,
  WardCategory,
} from "./schema";

export const HOSPITAL = {
  name: "HIMS Simulation",
  shortName: "HIMS Simulation",
  address: "Plot 14, Baner–Pashan Link Road, Pune 411045",
  phone: "020 4100 2200",
  gstin: "27AAACH0000X1Z5",
  /** Clinic hours, "today" and rosters follow the hospital's local time. */
  timeZone: "Asia/Kolkata",
};

export const DEPARTMENTS: Array<{
  code: string;
  name: string;
  kind: DepartmentKind;
  location: string;
}> = [
  {
    code: "GEN",
    name: "General Medicine",
    kind: "CLINICAL",
    location: "OPD Block A · Rooms 101–103",
  },
  {
    code: "PED",
    name: "Paediatrics",
    kind: "CLINICAL",
    location: "OPD Block A · Rooms 104–105",
  },
  {
    code: "ORT",
    name: "Orthopaedics",
    kind: "CLINICAL",
    location: "OPD Block A · Rooms 110–111",
  },
  {
    code: "CAR",
    name: "Cardiology",
    kind: "CLINICAL",
    location: "OPD Block B · Rooms 201–202",
  },
  {
    code: "OBG",
    name: "Obstetrics & Gynaecology",
    kind: "CLINICAL",
    location: "OPD Block B · Rooms 210–211",
  },
  {
    code: "ENT",
    name: "ENT",
    kind: "CLINICAL",
    location: "OPD Block C · Room 105",
  },
  {
    code: "DER",
    name: "Dermatology",
    kind: "CLINICAL",
    location: "OPD Block C · Room 108",
  },
  {
    code: "SUR",
    name: "General Surgery",
    kind: "CLINICAL",
    location: "OPD Block B · Rooms 215–216",
  },
  {
    code: "LAB",
    name: "Laboratory Services",
    kind: "DIAGNOSTIC",
    location: "Block D · Ground floor",
  },
  {
    code: "PHA",
    name: "Pharmacy",
    kind: "SUPPORT",
    location: "Block A · Ground floor",
  },
  {
    code: "NUR",
    name: "Nursing Services",
    kind: "SUPPORT",
    location: "Nursing station · Floors 1–4",
  },
  {
    code: "FRO",
    name: "Front Office",
    kind: "ADMINISTRATIVE",
    location: "Main lobby",
  },
  {
    code: "BIL",
    name: "Billing & Accounts",
    kind: "ADMINISTRATIVE",
    location: "Main lobby · Counter 3–5",
  },
  {
    code: "MRD",
    name: "Medical Records",
    kind: "ADMINISTRATIVE",
    location: "Block D · Basement",
  },
  {
    code: "OPS",
    name: "Hospital Operations",
    kind: "ADMINISTRATIVE",
    location: "Admin block · Floor 1",
  },
  {
    code: "HKP",
    name: "Housekeeping",
    kind: "SUPPORT",
    location: "Service block",
  },
];

export interface StaffSeed {
  first: string;
  last: string;
  role: StaffRole;
  dept: string;
  designation: string;
  specialisation?: string;
  qualification?: string;
  fee?: number;
  /** Default login shown for the role on the sign-in screen. */
  primaryLogin?: boolean;
}

export const STAFF: StaffSeed[] = [
  {
    first: "Meera",
    last: "Iyer",
    role: "ADMINISTRATOR",
    dept: "OPS",
    designation: "Hospital Administrator",
    qualification: "MHA",
    primaryLogin: true,
  },
  {
    first: "Vikram",
    last: "Sethi",
    role: "OPERATIONS_MANAGER",
    dept: "OPS",
    designation: "Operations Manager",
    qualification: "MBA (Healthcare)",
    primaryLogin: true,
  },
  {
    first: "Nandini",
    last: "Rao",
    role: "OPERATIONS_MANAGER",
    dept: "OPS",
    designation: "Patient Experience Lead",
  },

  {
    first: "Arjun",
    last: "Mehta",
    role: "DOCTOR",
    dept: "GEN",
    designation: "Senior Consultant",
    specialisation: "Internal Medicine",
    qualification: "MD (Medicine)",
    fee: 800,
    primaryLogin: true,
  },
  {
    first: "Sneha",
    last: "Kulkarni",
    role: "DOCTOR",
    dept: "GEN",
    designation: "Consultant",
    specialisation: "Diabetology",
    qualification: "MD, DNB",
    fee: 700,
  },
  {
    first: "Rohan",
    last: "Deshpande",
    role: "DOCTOR",
    dept: "PED",
    designation: "Consultant",
    specialisation: "Paediatrics",
    qualification: "MD (Paediatrics)",
    fee: 700,
  },
  {
    first: "Aisha",
    last: "Siddiqui",
    role: "DOCTOR",
    dept: "PED",
    designation: "Associate Consultant",
    specialisation: "Neonatology",
    qualification: "DCH, DNB",
    fee: 600,
  },
  {
    first: "Karthik",
    last: "Subramanian",
    role: "DOCTOR",
    dept: "ORT",
    designation: "Senior Consultant",
    specialisation: "Joint Replacement",
    qualification: "MS (Ortho)",
    fee: 900,
  },
  {
    first: "Prakash",
    last: "Joshi",
    role: "DOCTOR",
    dept: "ORT",
    designation: "Consultant",
    specialisation: "Trauma & Spine",
    qualification: "MS (Ortho)",
    fee: 800,
  },
  {
    first: "Ananya",
    last: "Bose",
    role: "DOCTOR",
    dept: "CAR",
    designation: "Senior Consultant",
    specialisation: "Interventional Cardiology",
    qualification: "DM (Cardiology)",
    fee: 1200,
  },
  {
    first: "Siddharth",
    last: "Nair",
    role: "DOCTOR",
    dept: "CAR",
    designation: "Consultant",
    specialisation: "Cardiology",
    qualification: "DM (Cardiology)",
    fee: 1000,
  },
  {
    first: "Lakshmi",
    last: "Venkatesh",
    role: "DOCTOR",
    dept: "OBG",
    designation: "Senior Consultant",
    specialisation: "High-risk Obstetrics",
    qualification: "MS (OBG)",
    fee: 900,
  },
  {
    first: "Priya",
    last: "Chauhan",
    role: "DOCTOR",
    dept: "OBG",
    designation: "Consultant",
    specialisation: "Gynaecology",
    qualification: "DGO, DNB",
    fee: 700,
  },
  {
    first: "Manoj",
    last: "Pillai",
    role: "DOCTOR",
    dept: "ENT",
    designation: "Consultant",
    specialisation: "Otorhinolaryngology",
    qualification: "MS (ENT)",
    fee: 700,
  },
  {
    first: "Ritu",
    last: "Agarwal",
    role: "DOCTOR",
    dept: "DER",
    designation: "Consultant",
    specialisation: "Dermatology",
    qualification: "MD (DVL)",
    fee: 700,
  },
  {
    first: "Faisal",
    last: "Qureshi",
    role: "DOCTOR",
    dept: "SUR",
    designation: "Senior Consultant",
    specialisation: "Laparoscopic Surgery",
    qualification: "MS (Surgery)",
    fee: 900,
  },
  {
    first: "Gaurav",
    last: "Bhatt",
    role: "DOCTOR",
    dept: "SUR",
    designation: "Consultant",
    specialisation: "General Surgery",
    qualification: "MS, FMAS",
    fee: 800,
  },

  {
    first: "Anita",
    last: "D'Souza",
    role: "NURSE",
    dept: "NUR",
    designation: "Nursing Supervisor",
    qualification: "M.Sc Nursing",
    primaryLogin: true,
  },
  {
    first: "Reshma",
    last: "Patil",
    role: "NURSE",
    dept: "NUR",
    designation: "Staff Nurse",
    qualification: "B.Sc Nursing",
  },
  {
    first: "Jincy",
    last: "Thomas",
    role: "NURSE",
    dept: "NUR",
    designation: "Staff Nurse",
    qualification: "B.Sc Nursing",
  },
  {
    first: "Kavya",
    last: "Shetty",
    role: "NURSE",
    dept: "NUR",
    designation: "Staff Nurse",
    qualification: "GNM",
  },
  {
    first: "Mary",
    last: "Joseph",
    role: "NURSE",
    dept: "NUR",
    designation: "Ward In-charge",
    qualification: "B.Sc Nursing",
  },
  {
    first: "Sunita",
    last: "Gaikwad",
    role: "NURSE",
    dept: "NUR",
    designation: "Staff Nurse",
    qualification: "GNM",
  },
  {
    first: "Deepa",
    last: "Menon",
    role: "NURSE",
    dept: "NUR",
    designation: "Staff Nurse",
    qualification: "B.Sc Nursing",
  },
  {
    first: "Rahul",
    last: "Kamble",
    role: "NURSE",
    dept: "NUR",
    designation: "Staff Nurse",
    qualification: "GNM",
  },
  {
    first: "Shalini",
    last: "More",
    role: "NURSE",
    dept: "NUR",
    designation: "OPD Nurse",
    qualification: "ANM",
  },
  {
    first: "Tessy",
    last: "Varghese",
    role: "NURSE",
    dept: "NUR",
    designation: "HDU Nurse",
    qualification: "B.Sc Nursing",
  },
  {
    first: "Pradnya",
    last: "Jadhav",
    role: "NURSE",
    dept: "NUR",
    designation: "Staff Nurse",
    qualification: "GNM",
  },
  {
    first: "Neha",
    last: "Sawant",
    role: "NURSE",
    dept: "NUR",
    designation: "OPD Nurse",
    qualification: "ANM",
  },

  {
    first: "Rahul",
    last: "Verma",
    role: "PHARMACIST",
    dept: "PHA",
    designation: "Chief Pharmacist",
    qualification: "M.Pharm",
    primaryLogin: true,
  },
  {
    first: "Swati",
    last: "Khandelwal",
    role: "PHARMACIST",
    dept: "PHA",
    designation: "Pharmacist",
    qualification: "B.Pharm",
  },
  {
    first: "Imran",
    last: "Shaikh",
    role: "PHARMACIST",
    dept: "PHA",
    designation: "Pharmacist",
    qualification: "D.Pharm",
  },

  {
    first: "Kavita",
    last: "Rao",
    role: "LAB_TECHNICIAN",
    dept: "LAB",
    designation: "Senior Lab Technologist",
    qualification: "M.Sc MLT",
    primaryLogin: true,
  },
  {
    first: "Amit",
    last: "Sharma",
    role: "LAB_TECHNICIAN",
    dept: "LAB",
    designation: "Lab Technician",
    qualification: "B.Sc MLT",
  },
  {
    first: "Pooja",
    last: "Bhosale",
    role: "LAB_TECHNICIAN",
    dept: "LAB",
    designation: "Phlebotomist",
    qualification: "DMLT",
  },
  {
    first: "Sameer",
    last: "Kulkarni",
    role: "LAB_TECHNICIAN",
    dept: "LAB",
    designation: "Lab Technician",
    qualification: "B.Sc MLT",
  },

  {
    first: "Pooja",
    last: "Nair",
    role: "RECEPTIONIST",
    dept: "FRO",
    designation: "Front Office Executive",
    primaryLogin: true,
  },
  {
    first: "Aditya",
    last: "Kale",
    role: "RECEPTIONIST",
    dept: "FRO",
    designation: "Front Office Executive",
  },
  {
    first: "Heena",
    last: "Mistry",
    role: "RECEPTIONIST",
    dept: "FRO",
    designation: "Patient Relations Executive",
  },

  {
    first: "Suresh",
    last: "Pillai",
    role: "BILLING_EXECUTIVE",
    dept: "BIL",
    designation: "Billing Supervisor",
    primaryLogin: true,
  },
  {
    first: "Nikita",
    last: "Deshmukh",
    role: "BILLING_EXECUTIVE",
    dept: "BIL",
    designation: "Billing Executive",
  },
  {
    first: "Harish",
    last: "Rane",
    role: "BILLING_EXECUTIVE",
    dept: "BIL",
    designation: "Cashier",
  },

  {
    first: "Farah",
    last: "Khan",
    role: "MRD_STAFF",
    dept: "MRD",
    designation: "Medical Records Officer",
    qualification: "B.Sc MRT",
    primaryLogin: true,
  },
  {
    first: "Ganesh",
    last: "Pawar",
    role: "MRD_STAFF",
    dept: "MRD",
    designation: "Records Assistant",
  },

  {
    first: "Babu",
    last: "Shinde",
    role: "SUPPORT",
    dept: "HKP",
    designation: "Housekeeping Supervisor",
  },
  {
    first: "Lata",
    last: "Waghmare",
    role: "SUPPORT",
    dept: "HKP",
    designation: "Housekeeping Staff",
  },
  {
    first: "Santosh",
    last: "Chavan",
    role: "SUPPORT",
    dept: "HKP",
    designation: "Housekeeping Staff",
  },
];

export const SHIFTS = [
  { code: "M", name: "Morning", start: "08:00", end: "14:00" },
  { code: "E", name: "Evening", start: "14:00", end: "20:00" },
  { code: "N", name: "Night", start: "20:00", end: "08:00" },
  { code: "G", name: "General", start: "09:00", end: "17:00" },
];

export const WARDS: Array<{
  code: string;
  name: string;
  floor: number;
  category: WardCategory;
  dept?: string;
  dailyRate: number;
  restriction?: { gender?: "MALE" | "FEMALE"; maxAge?: number };
  rooms: Array<{ number: string; beds: number }>;
}> = [
  {
    code: "HDU",
    name: "High Dependency Unit",
    floor: 1,
    category: "HDU",
    dept: "CAR",
    dailyRate: 9000,
    rooms: [{ number: "HDU", beds: 4 }],
  },
  {
    code: "GWM",
    name: "General Ward (Male)",
    floor: 2,
    category: "GENERAL",
    dept: "GEN",
    dailyRate: 1500,
    restriction: { gender: "MALE" },
    rooms: [
      { number: "201", beds: 4 },
      { number: "202", beds: 4 },
      { number: "203", beds: 4 },
    ],
  },
  {
    code: "GWF",
    name: "General Ward (Female)",
    floor: 2,
    category: "GENERAL",
    dept: "OBG",
    dailyRate: 1500,
    restriction: { gender: "FEMALE" },
    rooms: [
      { number: "211", beds: 4 },
      { number: "212", beds: 4 },
      { number: "213", beds: 4 },
    ],
  },
  {
    code: "PAE",
    name: "Paediatric Ward",
    floor: 3,
    category: "GENERAL",
    dept: "PED",
    dailyRate: 1800,
    restriction: { maxAge: 14 },
    rooms: [{ number: "301", beds: 4 }],
  },
  {
    code: "SPV",
    name: "Semi-Private",
    floor: 3,
    category: "SEMI_PRIVATE",
    dailyRate: 3200,
    rooms: [
      { number: "311", beds: 2 },
      { number: "312", beds: 2 },
      { number: "313", beds: 2 },
    ],
  },
  {
    code: "PVT",
    name: "Private Rooms",
    floor: 4,
    category: "PRIVATE",
    dailyRate: 5500,
    rooms: [
      { number: "401", beds: 1 },
      { number: "402", beds: 1 },
      { number: "403", beds: 1 },
      { number: "404", beds: 1 },
      { number: "405", beds: 1 },
    ],
  },
];

export interface MedicineSeed {
  code: string;
  name: string;
  generic: string;
  form: MedicineForm;
  strength: string;
  unit: string;
  category: string;
  price: number;
  reorder: number;
  maker: string;
  /** Units received in the opening stock; low values create shortages. */
  opening: number;
}

/**
 * Medicines a pharmacy may sell over the counter; everything else (and every
 * injection or infusion) is Schedule H / H1 / X — prescription only.
 */
const OTC_CATEGORIES = new Set([
  "Analgesic / antipyretic",
  "Antihistamine",
  "Antitussive",
  "Haematinic",
  "Supplement",
]);

export function isPrescriptionOnly(m: Pick<MedicineSeed, "category" | "form">) {
  if (m.form === "INJECTION" || m.form === "INFUSION") return true;
  return !OTC_CATEGORIES.has(m.category);
}

/** Fictional pharmaceutical distributors for goods receipts. */
export const SUPPLIERS = [
  "Sahyadri Pharma Distributors",
  "Deccan Medisales Pvt Ltd",
  "Konkan Healthcare Agencies",
  "Western Surgicals & Pharma",
];

export const MEDICINES: MedicineSeed[] = [
  {
    code: "PCM500",
    name: "Paracetamol",
    generic: "Paracetamol",
    form: "TABLET",
    strength: "500 mg",
    unit: "tablet",
    category: "Analgesic / antipyretic",
    price: 2,
    reorder: 400,
    maker: "Cipla",
    opening: 3000,
  },
  {
    code: "PCM650",
    name: "Dolo",
    generic: "Paracetamol",
    form: "TABLET",
    strength: "650 mg",
    unit: "tablet",
    category: "Analgesic / antipyretic",
    price: 3,
    reorder: 400,
    maker: "Micro Labs",
    opening: 3000,
  },
  {
    code: "PCMSYR",
    name: "Calpol Syrup",
    generic: "Paracetamol",
    form: "SYRUP",
    strength: "120 mg/5 ml · 60 ml",
    unit: "bottle",
    category: "Analgesic / antipyretic",
    price: 38,
    reorder: 30,
    maker: "GSK",
    opening: 160,
  },
  {
    code: "AMX500",
    name: "Mox",
    generic: "Amoxicillin",
    form: "CAPSULE",
    strength: "500 mg",
    unit: "capsule",
    category: "Penicillin antibiotic",
    price: 8,
    reorder: 200,
    maker: "Sun Pharma",
    opening: 1200,
  },
  {
    code: "AMXSYR",
    name: "Mox Dry Syrup",
    generic: "Amoxicillin",
    form: "SYRUP",
    strength: "125 mg/5 ml · 60 ml",
    unit: "bottle",
    category: "Penicillin antibiotic",
    price: 68,
    reorder: 20,
    maker: "Sun Pharma",
    opening: 90,
  },
  {
    code: "AMC625",
    name: "Augmentin",
    generic: "Amoxicillin + Clavulanate",
    form: "TABLET",
    strength: "625 mg",
    unit: "tablet",
    category: "Penicillin antibiotic",
    price: 22,
    reorder: 150,
    maker: "GSK",
    opening: 900,
  },
  {
    code: "AZI500",
    name: "Azithral",
    generic: "Azithromycin",
    form: "TABLET",
    strength: "500 mg",
    unit: "tablet",
    category: "Macrolide antibiotic",
    price: 25,
    reorder: 100,
    maker: "Alembic",
    opening: 600,
  },
  {
    code: "CFX200",
    name: "Taxim-O",
    generic: "Cefixime",
    form: "TABLET",
    strength: "200 mg",
    unit: "tablet",
    category: "Cephalosporin antibiotic",
    price: 14,
    reorder: 100,
    maker: "Alkem",
    opening: 500,
  },
  {
    code: "CTR1G",
    name: "Monocef",
    generic: "Ceftriaxone",
    form: "INJECTION",
    strength: "1 g vial",
    unit: "vial",
    category: "Cephalosporin antibiotic",
    price: 65,
    reorder: 80,
    maker: "Aristo",
    opening: 700,
  },
  {
    code: "MTZ400",
    name: "Metrogyl",
    generic: "Metronidazole",
    form: "TABLET",
    strength: "400 mg",
    unit: "tablet",
    category: "Antiprotozoal",
    price: 3,
    reorder: 150,
    maker: "J B Chemicals",
    opening: 800,
  },
  {
    code: "MTZIV",
    name: "Metrogyl IV",
    generic: "Metronidazole",
    form: "INFUSION",
    strength: "500 mg/100 ml",
    unit: "bottle",
    category: "Antiprotozoal",
    price: 32,
    reorder: 60,
    maker: "J B Chemicals",
    opening: 400,
  },
  {
    code: "PAN40",
    name: "Pan",
    generic: "Pantoprazole",
    form: "TABLET",
    strength: "40 mg",
    unit: "tablet",
    category: "Proton pump inhibitor",
    price: 7,
    reorder: 300,
    maker: "Alkem",
    opening: 2000,
  },
  {
    code: "PANIV",
    name: "Pan IV",
    generic: "Pantoprazole",
    form: "INJECTION",
    strength: "40 mg vial",
    unit: "vial",
    category: "Proton pump inhibitor",
    price: 55,
    reorder: 80,
    maker: "Alkem",
    opening: 500,
  },
  {
    code: "OND4",
    name: "Emeset",
    generic: "Ondansetron",
    form: "TABLET",
    strength: "4 mg",
    unit: "tablet",
    category: "Antiemetic",
    price: 6,
    reorder: 150,
    maker: "Cipla",
    opening: 700,
  },
  {
    code: "ONDIV",
    name: "Emeset Injection",
    generic: "Ondansetron",
    form: "INJECTION",
    strength: "2 mg/ml · 2 ml",
    unit: "ampoule",
    category: "Antiemetic",
    price: 18,
    reorder: 60,
    maker: "Cipla",
    opening: 300,
  },
  {
    code: "DOM10",
    name: "Domstal",
    generic: "Domperidone",
    form: "TABLET",
    strength: "10 mg",
    unit: "tablet",
    category: "Antiemetic",
    price: 3,
    reorder: 100,
    maker: "Torrent",
    opening: 500,
  },
  {
    code: "MET500",
    name: "Glycomet",
    generic: "Metformin",
    form: "TABLET",
    strength: "500 mg",
    unit: "tablet",
    category: "Antidiabetic",
    price: 3,
    reorder: 500,
    maker: "USV",
    opening: 3500,
  },
  {
    code: "GLM2",
    name: "Amaryl",
    generic: "Glimepiride",
    form: "TABLET",
    strength: "2 mg",
    unit: "tablet",
    category: "Antidiabetic",
    price: 6,
    reorder: 300,
    maker: "Sanofi",
    opening: 1500,
  },
  {
    code: "INSGL",
    name: "Basalog Pen",
    generic: "Insulin glargine",
    form: "INJECTION",
    strength: "100 IU/ml · 3 ml",
    unit: "pen",
    category: "Insulin",
    price: 620,
    reorder: 10,
    maker: "Biocon",
    opening: 24,
  },
  {
    code: "AML5",
    name: "Amlong",
    generic: "Amlodipine",
    form: "TABLET",
    strength: "5 mg",
    unit: "tablet",
    category: "Antihypertensive",
    price: 4,
    reorder: 400,
    maker: "Micro Labs",
    opening: 2500,
  },
  {
    code: "TEL40",
    name: "Telma",
    generic: "Telmisartan",
    form: "TABLET",
    strength: "40 mg",
    unit: "tablet",
    category: "Antihypertensive",
    price: 7,
    reorder: 400,
    maker: "Glenmark",
    opening: 2500,
  },
  {
    code: "ATV20",
    name: "Atorva",
    generic: "Atorvastatin",
    form: "TABLET",
    strength: "20 mg",
    unit: "tablet",
    category: "Statin",
    price: 9,
    reorder: 300,
    maker: "Zydus",
    opening: 1800,
  },
  {
    code: "ASP75",
    name: "Ecosprin",
    generic: "Aspirin",
    form: "TABLET",
    strength: "75 mg",
    unit: "tablet",
    category: "Antiplatelet",
    price: 2,
    reorder: 300,
    maker: "USV",
    opening: 1800,
  },
  {
    code: "CLP75",
    name: "Clopilet",
    generic: "Clopidogrel",
    form: "TABLET",
    strength: "75 mg",
    unit: "tablet",
    category: "Antiplatelet",
    price: 8,
    reorder: 200,
    maker: "Sun Pharma",
    opening: 1000,
  },
  {
    code: "ENX40",
    name: "Clexane",
    generic: "Enoxaparin",
    form: "INJECTION",
    strength: "40 mg/0.4 ml",
    unit: "syringe",
    category: "Anticoagulant",
    price: 380,
    reorder: 30,
    maker: "Sanofi",
    opening: 120,
  },
  {
    code: "FUR40",
    name: "Lasix",
    generic: "Furosemide",
    form: "TABLET",
    strength: "40 mg",
    unit: "tablet",
    category: "Diuretic",
    price: 2,
    reorder: 100,
    maker: "Sanofi",
    opening: 400,
  },
  {
    code: "FURIV",
    name: "Lasix Injection",
    generic: "Furosemide",
    form: "INJECTION",
    strength: "10 mg/ml · 2 ml",
    unit: "ampoule",
    category: "Diuretic",
    price: 12,
    reorder: 40,
    maker: "Sanofi",
    opening: 150,
  },
  {
    code: "SAL100",
    name: "Asthalin Inhaler",
    generic: "Salbutamol",
    form: "INHALER",
    strength: "100 mcg/dose",
    unit: "inhaler",
    category: "Bronchodilator",
    price: 145,
    reorder: 15,
    maker: "Cipla",
    opening: 60,
  },
  {
    code: "MON10",
    name: "Montair",
    generic: "Montelukast",
    form: "TABLET",
    strength: "10 mg",
    unit: "tablet",
    category: "Anti-asthmatic",
    price: 12,
    reorder: 150,
    maker: "Cipla",
    opening: 600,
  },
  {
    code: "CET10",
    name: "Cetzine",
    generic: "Cetirizine",
    form: "TABLET",
    strength: "10 mg",
    unit: "tablet",
    category: "Antihistamine",
    price: 2,
    reorder: 200,
    maker: "Dr Reddy's",
    opening: 1200,
  },
  {
    code: "LCZ5",
    name: "Levocet",
    generic: "Levocetirizine",
    form: "TABLET",
    strength: "5 mg",
    unit: "tablet",
    category: "Antihistamine",
    price: 3,
    reorder: 200,
    maker: "Hetero",
    opening: 900,
  },
  {
    code: "IBU400",
    name: "Brufen",
    generic: "Ibuprofen",
    form: "TABLET",
    strength: "400 mg",
    unit: "tablet",
    category: "NSAID analgesic",
    price: 3,
    reorder: 200,
    maker: "Abbott",
    opening: 1000,
  },
  {
    code: "DIC50",
    name: "Voveran",
    generic: "Diclofenac",
    form: "TABLET",
    strength: "50 mg",
    unit: "tablet",
    category: "NSAID analgesic",
    price: 3,
    reorder: 200,
    maker: "Novartis",
    opening: 1000,
  },
  {
    code: "TRM50",
    name: "Ultracet",
    generic: "Tramadol + Paracetamol",
    form: "TABLET",
    strength: "37.5/325 mg",
    unit: "tablet",
    category: "Opioid analgesic",
    price: 11,
    reorder: 100,
    maker: "Janssen",
    opening: 60,
  },
  {
    code: "CAD3",
    name: "Shelcal",
    generic: "Calcium + Vitamin D3",
    form: "TABLET",
    strength: "500 mg/250 IU",
    unit: "tablet",
    category: "Supplement",
    price: 6,
    reorder: 300,
    maker: "Torrent",
    opening: 1500,
  },
  {
    code: "FER100",
    name: "Orofer XT",
    generic: "Ferrous ascorbate + Folic acid",
    form: "TABLET",
    strength: "100 mg/1.5 mg",
    unit: "tablet",
    category: "Haematinic",
    price: 9,
    reorder: 200,
    maker: "Emcure",
    opening: 900,
  },
  {
    code: "FOL5",
    name: "Folvite",
    generic: "Folic acid",
    form: "TABLET",
    strength: "5 mg",
    unit: "tablet",
    category: "Supplement",
    price: 2,
    reorder: 200,
    maker: "Pfizer",
    opening: 800,
  },
  {
    code: "BCX",
    name: "Becosules",
    generic: "Vitamin B-complex",
    form: "CAPSULE",
    strength: "—",
    unit: "capsule",
    category: "Supplement",
    price: 3,
    reorder: 200,
    maker: "Pfizer",
    opening: 1000,
  },
  {
    code: "LEV500",
    name: "Levoflox",
    generic: "Levofloxacin",
    form: "TABLET",
    strength: "500 mg",
    unit: "tablet",
    category: "Fluoroquinolone antibiotic",
    price: 12,
    reorder: 80,
    maker: "Cipla",
    opening: 40,
  },
  {
    code: "NS500",
    name: "Normal Saline",
    generic: "Sodium chloride 0.9%",
    form: "INFUSION",
    strength: "500 ml",
    unit: "bottle",
    category: "IV fluid",
    price: 45,
    reorder: 150,
    maker: "Baxter",
    opening: 1200,
  },
  {
    code: "RL500",
    name: "Ringer Lactate",
    generic: "Compound sodium lactate",
    form: "INFUSION",
    strength: "500 ml",
    unit: "bottle",
    category: "IV fluid",
    price: 55,
    reorder: 100,
    maker: "Baxter",
    opening: 700,
  },
  {
    code: "DNS500",
    name: "Dextrose Normal Saline",
    generic: "Dextrose 5% + NaCl 0.9%",
    form: "INFUSION",
    strength: "500 ml",
    unit: "bottle",
    category: "IV fluid",
    price: 48,
    reorder: 100,
    maker: "Baxter",
    opening: 600,
  },
  {
    code: "HCT100",
    name: "Efcorlin",
    generic: "Hydrocortisone",
    form: "INJECTION",
    strength: "100 mg vial",
    unit: "vial",
    category: "Corticosteroid",
    price: 45,
    reorder: 30,
    maker: "Pfizer",
    opening: 90,
  },
  {
    code: "DXM",
    name: "Benadryl DR",
    generic: "Dextromethorphan",
    form: "SYRUP",
    strength: "100 ml",
    unit: "bottle",
    category: "Antitussive",
    price: 95,
    reorder: 30,
    maker: "J&J",
    opening: 150,
  },
  {
    code: "MUP5",
    name: "T-Bact",
    generic: "Mupirocin",
    form: "OINTMENT",
    strength: "2% · 5 g",
    unit: "tube",
    category: "Topical antibiotic",
    price: 110,
    reorder: 20,
    maker: "GSK",
    opening: 70,
  },
  {
    code: "CLT15",
    name: "Candid Cream",
    generic: "Clotrimazole",
    form: "OINTMENT",
    strength: "1% · 15 g",
    unit: "tube",
    category: "Antifungal",
    price: 85,
    reorder: 20,
    maker: "Glenmark",
    opening: 80,
  },
  {
    code: "BTM20",
    name: "Betnovate-N",
    generic: "Betamethasone + Neomycin",
    form: "OINTMENT",
    strength: "20 g",
    unit: "tube",
    category: "Topical steroid",
    price: 62,
    reorder: 20,
    maker: "GSK",
    opening: 70,
  },
  {
    code: "MOXED",
    name: "Vigamox",
    generic: "Moxifloxacin",
    form: "DROPS",
    strength: "0.5% · 5 ml",
    unit: "bottle",
    category: "Ophthalmic antibiotic",
    price: 120,
    reorder: 15,
    maker: "Novartis",
    opening: 40,
  },
  {
    code: "CIPED",
    name: "Ciplox Ear Drops",
    generic: "Ciprofloxacin",
    form: "DROPS",
    strength: "0.3% · 10 ml",
    unit: "bottle",
    category: "Otic antibiotic",
    price: 45,
    reorder: 15,
    maker: "Cipla",
    opening: 50,
  },
];

export interface LabTestSeed {
  code: string;
  name: string;
  section: string;
  sample: SampleType;
  price: number;
  tat: number;
  params: Array<Omit<LabParameter, "id">>;
}

const QUAL_NEG = ["Negative", "Positive"];

export const LAB_TESTS: LabTestSeed[] = [
  {
    code: "CBC",
    name: "Complete Blood Count",
    section: "Haematology",
    sample: "BLOOD",
    price: 350,
    tat: 4,
    params: [
      {
        name: "Haemoglobin",
        unit: "g/dL",
        refLow: 12,
        refHigh: 16,
        criticalLow: 7,
        criticalHigh: 20,
      },
      {
        name: "Total WBC count",
        unit: "×10³/µL",
        refLow: 4,
        refHigh: 11,
        criticalLow: 2,
        criticalHigh: 30,
      },
      {
        name: "Platelet count",
        unit: "×10³/µL",
        refLow: 150,
        refHigh: 450,
        criticalLow: 50,
        criticalHigh: 1000,
      },
      { name: "RBC count", unit: "×10⁶/µL", refLow: 4.2, refHigh: 5.9 },
      { name: "Haematocrit (PCV)", unit: "%", refLow: 36, refHigh: 48 },
    ],
  },
  {
    code: "ESR",
    name: "ESR",
    section: "Haematology",
    sample: "BLOOD",
    price: 150,
    tat: 2,
    params: [{ name: "ESR", unit: "mm/hr", refLow: 0, refHigh: 20 }],
  },
  {
    code: "FBS",
    name: "Blood Sugar — Fasting",
    section: "Biochemistry",
    sample: "BLOOD",
    price: 120,
    tat: 2,
    params: [
      {
        name: "Fasting glucose",
        unit: "mg/dL",
        refLow: 70,
        refHigh: 100,
        criticalLow: 45,
        criticalHigh: 400,
      },
    ],
  },
  {
    code: "PPBS",
    name: "Blood Sugar — Post-prandial",
    section: "Biochemistry",
    sample: "BLOOD",
    price: 120,
    tat: 2,
    params: [
      {
        name: "Post-prandial glucose",
        unit: "mg/dL",
        refLow: 70,
        refHigh: 140,
        criticalLow: 45,
        criticalHigh: 450,
      },
    ],
  },
  {
    code: "HBA1C",
    name: "HbA1c",
    section: "Biochemistry",
    sample: "BLOOD",
    price: 450,
    tat: 24,
    params: [{ name: "HbA1c", unit: "%", refLow: 4, refHigh: 5.6 }],
  },
  {
    code: "LFT",
    name: "Liver Function Test",
    section: "Biochemistry",
    sample: "SERUM",
    price: 650,
    tat: 6,
    params: [
      { name: "Total bilirubin", unit: "mg/dL", refLow: 0.2, refHigh: 1.2 },
      { name: "SGOT (AST)", unit: "U/L", refLow: 5, refHigh: 40 },
      { name: "SGPT (ALT)", unit: "U/L", refLow: 7, refHigh: 56 },
      { name: "Alkaline phosphatase", unit: "U/L", refLow: 44, refHigh: 147 },
      { name: "Albumin", unit: "g/dL", refLow: 3.5, refHigh: 5 },
    ],
  },
  {
    code: "KFT",
    name: "Kidney Function Test",
    section: "Biochemistry",
    sample: "SERUM",
    price: 600,
    tat: 6,
    params: [
      { name: "Blood urea", unit: "mg/dL", refLow: 15, refHigh: 40 },
      {
        name: "Serum creatinine",
        unit: "mg/dL",
        refLow: 0.6,
        refHigh: 1.3,
        criticalHigh: 6,
      },
      {
        name: "Sodium",
        unit: "mEq/L",
        refLow: 135,
        refHigh: 145,
        criticalLow: 120,
        criticalHigh: 160,
      },
      {
        name: "Potassium",
        unit: "mEq/L",
        refLow: 3.5,
        refHigh: 5.1,
        criticalLow: 2.8,
        criticalHigh: 6.2,
      },
    ],
  },
  {
    code: "LIPID",
    name: "Lipid Profile",
    section: "Biochemistry",
    sample: "SERUM",
    price: 700,
    tat: 12,
    params: [
      { name: "Total cholesterol", unit: "mg/dL", refLow: 125, refHigh: 200 },
      { name: "Triglycerides", unit: "mg/dL", refLow: 40, refHigh: 150 },
      { name: "HDL cholesterol", unit: "mg/dL", refLow: 40, refHigh: 80 },
      { name: "LDL cholesterol", unit: "mg/dL", refLow: 50, refHigh: 100 },
    ],
  },
  {
    code: "TSH",
    name: "Thyroid Stimulating Hormone",
    section: "Immunoassay",
    sample: "SERUM",
    price: 450,
    tat: 24,
    params: [{ name: "TSH", unit: "µIU/mL", refLow: 0.4, refHigh: 4 }],
  },
  {
    code: "CRP",
    name: "C-Reactive Protein",
    section: "Immunoassay",
    sample: "SERUM",
    price: 500,
    tat: 4,
    params: [{ name: "CRP", unit: "mg/L", refLow: 0, refHigh: 6 }],
  },
  {
    code: "TROP",
    name: "Troponin I (high sensitivity)",
    section: "Immunoassay",
    sample: "SERUM",
    price: 1200,
    tat: 1,
    params: [
      {
        name: "Troponin I",
        unit: "ng/mL",
        refLow: 0,
        refHigh: 0.04,
        criticalHigh: 0.4,
      },
    ],
  },
  {
    code: "URINE",
    name: "Urine Routine & Microscopy",
    section: "Clinical Pathology",
    sample: "URINE",
    price: 200,
    tat: 3,
    params: [
      {
        name: "Albumin",
        unit: "",
        refText: "Negative",
        options: ["Negative", "Trace", "1+", "2+", "3+"],
      },
      {
        name: "Sugar",
        unit: "",
        refText: "Negative",
        options: ["Negative", "Trace", "1+", "2+", "3+"],
      },
      { name: "Pus cells", unit: "/hpf", refLow: 0, refHigh: 5 },
      { name: "RBCs", unit: "/hpf", refLow: 0, refHigh: 2 },
    ],
  },
  {
    code: "NS1",
    name: "Dengue NS1 Antigen",
    section: "Serology",
    sample: "SERUM",
    price: 800,
    tat: 6,
    params: [
      { name: "NS1 antigen", unit: "", refText: "Negative", options: QUAL_NEG },
    ],
  },
  {
    code: "MPAG",
    name: "Malaria Antigen (Pf/Pv)",
    section: "Serology",
    sample: "BLOOD",
    price: 400,
    tat: 2,
    params: [
      {
        name: "Malaria antigen",
        unit: "",
        refText: "Negative",
        options: QUAL_NEG,
      },
    ],
  },
  {
    code: "WIDAL",
    name: "Widal Test",
    section: "Serology",
    sample: "SERUM",
    price: 300,
    tat: 6,
    params: [
      {
        name: "S. Typhi O titre",
        unit: "",
        refText: "< 1:80",
        options: ["< 1:80", "1:80", "1:160", "1:320"],
      },
    ],
  },
  {
    code: "BCS",
    name: "Blood Culture & Sensitivity",
    section: "Microbiology",
    sample: "BLOOD",
    price: 1100,
    tat: 72,
    params: [
      {
        name: "Culture",
        unit: "",
        refText: "No growth",
        options: ["No growth", "Growth detected"],
      },
    ],
  },
  {
    code: "AFB",
    name: "Sputum for AFB",
    section: "Microbiology",
    sample: "SPUTUM",
    price: 250,
    tat: 24,
    params: [
      {
        name: "Acid-fast bacilli",
        unit: "",
        refText: "Not seen",
        options: ["Not seen", "Seen"],
      },
    ],
  },
];

/* ------------------------------------------------------------------ */
/* Clinical templates — used by the seed to write believable visits     */
/* ------------------------------------------------------------------ */

export interface MedTemplate {
  code: string;
  dose: string;
  frequency: Frequency;
  route: Route;
  days: number;
  instructions?: string;
}

export interface ConditionTemplate {
  dept: string;
  diagnosis: string;
  icd: string;
  complaint: string;
  history: string;
  exam: string;
  labs: string[];
  meds: MedTemplate[];
  advice: string;
  /** Relative frequency within the department. */
  weight: number;
  ageRange?: [number, number];
  gender?: "MALE" | "FEMALE";
  /** Admission course for inpatient conditions. */
  inpatient?: {
    stay: [number, number];
    ward?: string;
    ivMeds: MedTemplate[];
    procedure?: { name: string; charge: number };
    course: string;
    dischargeMeds: MedTemplate[];
    diet: string;
  };
}

export const CONDITIONS: ConditionTemplate[] = [
  // General Medicine
  {
    dept: "GEN",
    diagnosis: "Acute febrile illness",
    icd: "R50.9",
    complaint: "Fever with body ache for 3 days",
    history:
      "Intermittent high-grade fever, no rash, no bleeding. No travel history.",
    exam: "Temp 38.6 °C, mild dehydration, chest clear, abdomen soft.",
    labs: ["CBC", "MPAG", "NS1"],
    meds: [
      {
        code: "PCM650",
        dose: "1 tablet",
        frequency: "TDS",
        route: "ORAL",
        days: 5,
        instructions: "After food; skip if no fever",
      },
      {
        code: "PAN40",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 5,
        instructions: "Before breakfast",
      },
    ],
    advice:
      "Oral fluids 3 L/day, rest, return if bleeding or persistent vomiting.",
    weight: 5,
  },
  {
    dept: "GEN",
    diagnosis: "Type 2 diabetes mellitus",
    icd: "E11.9",
    complaint: "Review of sugar control; increased thirst",
    history: "Known diabetic for 6 years on oral agents; irregular diet.",
    exam: "BMI 28, feet — no ulcers, peripheral pulses felt.",
    labs: ["FBS", "PPBS", "HBA1C"],
    meds: [
      {
        code: "MET500",
        dose: "1 tablet",
        frequency: "BD",
        route: "ORAL",
        days: 30,
        instructions: "After meals",
      },
      {
        code: "GLM2",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 30,
        instructions: "Before breakfast",
      },
    ],
    advice: "Diabetic diet, 30 minutes walk daily, home glucose log.",
    weight: 5,
    ageRange: [35, 75],
  },
  {
    dept: "GEN",
    diagnosis: "Essential hypertension",
    icd: "I10",
    complaint: "Headache and high BP readings at home",
    history: "BP 150/96 on home monitor over two weeks. Smoker.",
    exam: "BP 154/98 mmHg, heart sounds normal, no pedal oedema.",
    labs: ["KFT", "LIPID"],
    meds: [
      {
        code: "AML5",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 30,
      },
      {
        code: "TEL40",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 30,
      },
    ],
    advice: "Low salt diet, stop smoking, BP log twice a day.",
    weight: 4,
    ageRange: [35, 80],
  },
  {
    dept: "GEN",
    diagnosis: "Acute gastroenteritis",
    icd: "A09",
    complaint: "Loose stools and vomiting since yesterday",
    history: "6–7 watery stools, 3 episodes of vomiting, ate outside.",
    exam: "Mild dehydration, diffuse abdominal tenderness, no guarding.",
    labs: ["CBC", "KFT"],
    meds: [
      {
        code: "OND4",
        dose: "1 tablet",
        frequency: "TDS",
        route: "ORAL",
        days: 3,
        instructions: "Before food",
      },
      {
        code: "MTZ400",
        dose: "1 tablet",
        frequency: "TDS",
        route: "ORAL",
        days: 5,
      },
      {
        code: "PAN40",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 5,
      },
    ],
    advice: "ORS after every loose stool, light diet.",
    weight: 3,
  },
  {
    dept: "GEN",
    diagnosis: "Upper respiratory tract infection",
    icd: "J06.9",
    complaint: "Sore throat, cough and cold",
    history: "Dry cough for 4 days, low-grade fever, nasal congestion.",
    exam: "Congested pharynx, chest clear.",
    labs: [],
    meds: [
      {
        code: "AZI500",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 3,
      },
      {
        code: "CET10",
        dose: "1 tablet",
        frequency: "HS",
        route: "ORAL",
        days: 5,
      },
      { code: "DXM", dose: "10 ml", frequency: "TDS", route: "ORAL", days: 5 },
    ],
    advice: "Warm saline gargles, steam inhalation.",
    weight: 4,
  },
  {
    dept: "GEN",
    diagnosis: "Hypothyroidism",
    icd: "E03.9",
    complaint: "Fatigue and weight gain",
    history: "Tiredness for 3 months, cold intolerance.",
    exam: "Dry skin, pulse 62/min.",
    labs: ["TSH", "CBC"],
    meds: [
      {
        code: "BCX",
        dose: "1 capsule",
        frequency: "OD",
        route: "ORAL",
        days: 30,
      },
    ],
    advice: "Repeat TSH in 6 weeks.",
    weight: 2,
    gender: "FEMALE",
  },
  {
    dept: "GEN",
    diagnosis: "Dengue fever with thrombocytopenia",
    icd: "A90",
    complaint: "High fever, body ache and falling platelets",
    history: "Fever for 4 days, NS1 positive outside, platelet count 62,000.",
    exam: "Temp 38.9 °C, petechiae on forearms, BP 104/70.",
    labs: ["CBC", "LFT", "NS1"],
    meds: [],
    advice: "Admit for monitoring and IV fluids.",
    weight: 1,
    inpatient: {
      stay: [3, 5],
      ivMeds: [
        {
          code: "NS500",
          dose: "500 ml",
          frequency: "TDS",
          route: "IV",
          days: 3,
        },
        {
          code: "PCM500",
          dose: "1 tablet",
          frequency: "QID",
          route: "ORAL",
          days: 3,
        },
        { code: "PANIV", dose: "40 mg", frequency: "OD", route: "IV", days: 3 },
      ],
      course:
        "Managed with IV fluids and antipyretics. Platelets monitored every 12 hours; nadir 38,000 on day 2, recovered to 1,24,000 at discharge. No bleeding manifestations.",
      dischargeMeds: [
        {
          code: "PCM500",
          dose: "1 tablet",
          frequency: "SOS",
          route: "ORAL",
          days: 3,
        },
      ],
      diet: "Soft diet, oral fluids 3 L/day",
    },
  },
  {
    dept: "GEN",
    diagnosis: "Community-acquired pneumonia",
    icd: "J18.9",
    complaint: "Fever, cough with sputum and breathlessness",
    history: "Productive cough for 5 days, breathless on exertion.",
    exam: "RR 26/min, SpO₂ 92% on air, crepitations right base.",
    labs: ["CBC", "CRP", "KFT", "BCS"],
    meds: [],
    advice: "Admit for IV antibiotics and oxygen.",
    weight: 1,
    ageRange: [40, 85],
    inpatient: {
      stay: [4, 7],
      ivMeds: [
        { code: "CTR1G", dose: "1 g", frequency: "BD", route: "IV", days: 5 },
        {
          code: "AZI500",
          dose: "1 tablet",
          frequency: "OD",
          route: "ORAL",
          days: 5,
        },
        { code: "PANIV", dose: "40 mg", frequency: "OD", route: "IV", days: 5 },
        {
          code: "NS500",
          dose: "500 ml",
          frequency: "BD",
          route: "IV",
          days: 2,
        },
      ],
      course:
        "Treated with IV ceftriaxone and oral azithromycin with supplemental oxygen for 48 hours. Afebrile from day 3; SpO₂ 97% on room air at discharge.",
      dischargeMeds: [
        {
          code: "CFX200",
          dose: "1 tablet",
          frequency: "BD",
          route: "ORAL",
          days: 5,
        },
      ],
      diet: "Normal diet, encourage fluids",
    },
  },

  // Paediatrics
  {
    dept: "PED",
    diagnosis: "Viral fever",
    icd: "B34.9",
    complaint: "Fever and poor feeding for 2 days",
    history:
      "Fever up to 102 °F, active between spikes, immunised as per schedule.",
    exam: "Temp 38.4 °C, throat mildly congested, well hydrated.",
    labs: ["CBC"],
    meds: [
      {
        code: "PCMSYR",
        dose: "5 ml",
        frequency: "TDS",
        route: "ORAL",
        days: 3,
        instructions: "Only when temperature above 100 °F",
      },
    ],
    advice: "Plenty of fluids, sponge bath for fever.",
    weight: 5,
    ageRange: [1, 12],
  },
  {
    dept: "PED",
    diagnosis: "Acute otitis media",
    icd: "H66.9",
    complaint: "Ear pain and fever",
    history: "Right ear pain since last night, cold for 4 days.",
    exam: "Right tympanic membrane bulging and congested.",
    labs: [],
    meds: [
      {
        code: "AMXSYR",
        dose: "5 ml",
        frequency: "TDS",
        route: "ORAL",
        days: 7,
      },
      {
        code: "PCMSYR",
        dose: "5 ml",
        frequency: "SOS",
        route: "ORAL",
        days: 3,
      },
    ],
    advice: "Complete antibiotic course; review in 1 week.",
    weight: 3,
    ageRange: [1, 10],
  },
  {
    dept: "PED",
    diagnosis: "Acute bronchiolitis",
    icd: "J21.9",
    complaint: "Fast breathing and wheeze",
    history: "Cough and cold for 3 days, now breathing fast, feeding less.",
    exam: "RR 58/min, subcostal retractions, bilateral wheeze, SpO₂ 91%.",
    labs: ["CBC", "CRP"],
    meds: [],
    advice: "Admit for oxygen and nebulisation.",
    weight: 1,
    ageRange: [0, 2],
    inpatient: {
      stay: [2, 4],
      ward: "PAE",
      ivMeds: [
        {
          code: "SAL100",
          dose: "2 puffs via spacer",
          frequency: "QID",
          route: "INHALED",
          days: 3,
        },
        {
          code: "PCMSYR",
          dose: "2.5 ml",
          frequency: "SOS",
          route: "ORAL",
          days: 3,
        },
      ],
      course:
        "Oxygen by nasal prongs for 36 hours, salbutamol via spacer, nasal saline. Feeding improved; weaned to room air by day 2.",
      dischargeMeds: [
        {
          code: "PCMSYR",
          dose: "2.5 ml",
          frequency: "SOS",
          route: "ORAL",
          days: 3,
        },
      ],
      diet: "Breastfeeds on demand",
    },
  },
  {
    dept: "PED",
    diagnosis: "Acute gastroenteritis with dehydration",
    icd: "A09",
    complaint: "Vomiting and loose stools, not passing urine",
    history: "10 loose stools since morning, lethargic.",
    exam: "Some dehydration, sunken eyes, CRT 3 s.",
    labs: ["CBC", "KFT"],
    meds: [],
    advice: "Admit for IV rehydration.",
    weight: 1,
    ageRange: [1, 8],
    inpatient: {
      stay: [2, 3],
      ward: "PAE",
      ivMeds: [
        {
          code: "RL500",
          dose: "250 ml",
          frequency: "BD",
          route: "IV",
          days: 2,
        },
        {
          code: "ONDIV",
          dose: "0.15 mg/kg",
          frequency: "BD",
          route: "IV",
          days: 1,
        },
      ],
      course:
        "IV rehydration for 24 hours followed by ORS. Stools reduced; tolerating feeds, passing urine well.",
      dischargeMeds: [
        {
          code: "PCMSYR",
          dose: "5 ml",
          frequency: "SOS",
          route: "ORAL",
          days: 3,
        },
      ],
      diet: "Age-appropriate diet, ORS",
    },
  },

  // Orthopaedics
  {
    dept: "ORT",
    diagnosis: "Mechanical low back pain",
    icd: "M54.5",
    complaint: "Lower back pain for 2 weeks",
    history: "Pain after lifting weight, no radiation, no bladder symptoms.",
    exam: "Paraspinal tenderness L4–L5, SLR negative, neuro intact.",
    labs: [],
    meds: [
      {
        code: "DIC50",
        dose: "1 tablet",
        frequency: "BD",
        route: "ORAL",
        days: 5,
        instructions: "After food",
      },
      {
        code: "PAN40",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 5,
      },
      {
        code: "CAD3",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 30,
      },
    ],
    advice: "Back extension exercises, avoid lifting heavy weights.",
    weight: 4,
    ageRange: [25, 65],
  },
  {
    dept: "ORT",
    diagnosis: "Primary osteoarthritis of knee",
    icd: "M17.9",
    complaint: "Bilateral knee pain on climbing stairs",
    history: "Gradual onset pain over 1 year, morning stiffness < 20 minutes.",
    exam: "Crepitus both knees, no effusion.",
    labs: ["ESR", "CRP"],
    meds: [
      {
        code: "PCM650",
        dose: "1 tablet",
        frequency: "BD",
        route: "ORAL",
        days: 10,
      },
      {
        code: "CAD3",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 30,
      },
    ],
    advice: "Quadriceps strengthening, weight reduction.",
    weight: 3,
    ageRange: [45, 80],
  },
  {
    dept: "ORT",
    diagnosis: "Ankle sprain",
    icd: "S93.4",
    complaint: "Twisting injury to left ankle",
    history: "Inversion injury while walking down stairs yesterday.",
    exam: "Swelling over lateral malleolus, able to bear weight.",
    labs: [],
    meds: [
      {
        code: "IBU400",
        dose: "1 tablet",
        frequency: "TDS",
        route: "ORAL",
        days: 5,
        instructions: "After food",
      },
    ],
    advice: "RICE, crepe bandage, review in 1 week.",
    weight: 2,
    ageRange: [15, 55],
  },
  {
    dept: "ORT",
    diagnosis: "Fracture shaft of femur",
    icd: "S72.3",
    complaint: "Pain and deformity of right thigh after road accident",
    history: "Two-wheeler accident, unable to bear weight.",
    exam: "Deformity right thigh, distal pulses present.",
    labs: ["CBC", "KFT"],
    meds: [],
    advice: "Admit for surgical fixation.",
    weight: 1,
    ageRange: [18, 70],
    inpatient: {
      stay: [5, 7],
      ivMeds: [
        { code: "CTR1G", dose: "1 g", frequency: "BD", route: "IV", days: 3 },
        {
          code: "TRM50",
          dose: "1 tablet",
          frequency: "TDS",
          route: "ORAL",
          days: 5,
        },
        { code: "ENX40", dose: "40 mg", frequency: "OD", route: "SC", days: 5 },
        {
          code: "NS500",
          dose: "500 ml",
          frequency: "BD",
          route: "IV",
          days: 2,
        },
      ],
      procedure: {
        name: "Intramedullary nailing — surgeon, OT & implant charges",
        charge: 68000,
      },
      course:
        "Underwent closed reduction and intramedullary nailing under spinal anaesthesia on day 1. Post-operative course uneventful; mobilised with walker on day 3.",
      dischargeMeds: [
        {
          code: "PCM650",
          dose: "1 tablet",
          frequency: "TDS",
          route: "ORAL",
          days: 7,
        },
        {
          code: "CAD3",
          dose: "1 tablet",
          frequency: "OD",
          route: "ORAL",
          days: 30,
        },
      ],
      diet: "Normal diet, high protein",
    },
  },

  // Cardiology
  {
    dept: "CAR",
    diagnosis: "Stable angina",
    icd: "I20.8",
    complaint: "Chest tightness on exertion",
    history: "Retrosternal discomfort on walking uphill, relieved by rest.",
    exam: "BP 138/86, heart sounds normal. ECG: non-specific ST changes.",
    labs: ["LIPID", "TROP", "KFT"],
    meds: [
      {
        code: "ASP75",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 30,
        instructions: "After lunch",
      },
      {
        code: "ATV20",
        dose: "1 tablet",
        frequency: "HS",
        route: "ORAL",
        days: 30,
      },
    ],
    advice: "Treadmill test scheduled, avoid heavy exertion.",
    weight: 3,
    ageRange: [40, 80],
  },
  {
    dept: "CAR",
    diagnosis: "Palpitations — evaluation",
    icd: "R00.2",
    complaint: "Episodes of fast heartbeat",
    history: "Intermittent palpitations for a month, lasting minutes.",
    exam: "Pulse 88 regular. ECG: sinus rhythm.",
    labs: ["TSH", "CBC", "KFT"],
    meds: [],
    advice: "Holter monitoring advised; limit caffeine.",
    weight: 2,
  },
  {
    dept: "CAR",
    diagnosis: "Hypertensive heart disease — review",
    icd: "I11.9",
    complaint: "Follow-up of blood pressure and breathlessness",
    history: "On two antihypertensives, mild exertional breathlessness.",
    exam: "BP 146/92, no pedal oedema.",
    labs: ["KFT", "LIPID"],
    meds: [
      {
        code: "TEL40",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 30,
      },
      {
        code: "ATV20",
        dose: "1 tablet",
        frequency: "HS",
        route: "ORAL",
        days: 30,
      },
    ],
    advice: "Salt restriction, daily weight.",
    weight: 2,
    ageRange: [45, 85],
  },
  {
    dept: "CAR",
    diagnosis: "Acute coronary syndrome — NSTEMI",
    icd: "I21.4",
    complaint: "Severe chest pain with sweating",
    history: "Chest pain for 2 hours radiating to the left arm.",
    exam: "BP 150/94, diaphoretic. ECG: ST depression V4–V6.",
    labs: ["TROP", "CBC", "KFT", "LIPID"],
    meds: [],
    advice: "Admit to HDU.",
    weight: 1,
    ageRange: [45, 85],
    inpatient: {
      stay: [4, 6],
      ward: "HDU",
      ivMeds: [
        {
          code: "ASP75",
          dose: "1 tablet",
          frequency: "OD",
          route: "ORAL",
          days: 5,
        },
        {
          code: "CLP75",
          dose: "1 tablet",
          frequency: "OD",
          route: "ORAL",
          days: 5,
        },
        {
          code: "ATV20",
          dose: "2 tablets",
          frequency: "HS",
          route: "ORAL",
          days: 5,
        },
        { code: "ENX40", dose: "40 mg", frequency: "BD", route: "SC", days: 3 },
      ],
      procedure: {
        name: "Coronary angiography — cath lab charges",
        charge: 18000,
      },
      course:
        "Managed as NSTEMI with dual antiplatelets, high-intensity statin and anticoagulation. Angiography on day 2 showed single-vessel disease; medical management advised. Pain-free from day 1.",
      dischargeMeds: [
        {
          code: "ASP75",
          dose: "1 tablet",
          frequency: "OD",
          route: "ORAL",
          days: 30,
        },
        {
          code: "CLP75",
          dose: "1 tablet",
          frequency: "OD",
          route: "ORAL",
          days: 30,
        },
        {
          code: "ATV20",
          dose: "2 tablets",
          frequency: "HS",
          route: "ORAL",
          days: 30,
        },
      ],
      diet: "Low fat, low salt cardiac diet",
    },
  },
  {
    dept: "CAR",
    diagnosis: "Acute decompensated heart failure",
    icd: "I50.9",
    complaint: "Breathlessness at rest and swelling of legs",
    history: "Orthopnoea for 3 days, reduced urine output.",
    exam: "RR 28, SpO₂ 90%, bilateral basal crepitations, pedal oedema.",
    labs: ["KFT", "CBC", "TROP"],
    meds: [],
    advice: "Admit to HDU for IV diuretics.",
    weight: 1,
    ageRange: [55, 90],
    inpatient: {
      stay: [4, 7],
      ward: "HDU",
      ivMeds: [
        { code: "FURIV", dose: "40 mg", frequency: "BD", route: "IV", days: 3 },
        {
          code: "TEL40",
          dose: "1 tablet",
          frequency: "OD",
          route: "ORAL",
          days: 5,
        },
      ],
      course:
        "IV furosemide with fluid restriction; net negative balance of 4 L over 3 days. Breathlessness settled; transitioned to oral diuretics.",
      dischargeMeds: [
        {
          code: "FUR40",
          dose: "1 tablet",
          frequency: "OD",
          route: "ORAL",
          days: 30,
        },
        {
          code: "TEL40",
          dose: "1 tablet",
          frequency: "OD",
          route: "ORAL",
          days: 30,
        },
      ],
      diet: "Fluid restriction 1.5 L/day, low salt",
    },
  },

  // Obstetrics & Gynaecology
  {
    dept: "OBG",
    diagnosis: "Antenatal check-up — normal pregnancy",
    icd: "Z34.9",
    complaint: "Routine antenatal visit",
    history: "Primigravida, 24 weeks by dates, fetal movements felt.",
    exam: "Fundal height corresponds to dates, FHS 144/min, BP 110/70.",
    labs: ["CBC", "URINE", "FBS"],
    meds: [
      {
        code: "FER100",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 30,
      },
      {
        code: "CAD3",
        dose: "1 tablet",
        frequency: "BD",
        route: "ORAL",
        days: 30,
      },
    ],
    advice: "Next visit in 4 weeks, anomaly scan report to be reviewed.",
    weight: 5,
    gender: "FEMALE",
    ageRange: [20, 38],
  },
  {
    dept: "OBG",
    diagnosis: "Polycystic ovarian syndrome",
    icd: "E28.2",
    complaint: "Irregular periods and acne",
    history: "Cycles every 45–60 days for a year, weight gain.",
    exam: "BMI 29, mild hirsutism.",
    labs: ["TSH", "FBS"],
    meds: [
      {
        code: "MET500",
        dose: "1 tablet",
        frequency: "BD",
        route: "ORAL",
        days: 30,
      },
      {
        code: "FOL5",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 30,
      },
    ],
    advice: "Weight reduction, pelvic ultrasound.",
    weight: 3,
    gender: "FEMALE",
    ageRange: [18, 35],
  },
  {
    dept: "OBG",
    diagnosis: "Abnormal uterine bleeding",
    icd: "N93.9",
    complaint: "Heavy periods for 3 months",
    history: "Menses lasting 8–9 days with clots.",
    exam: "Pallor present, uterus bulky.",
    labs: ["CBC", "TSH"],
    meds: [
      {
        code: "FER100",
        dose: "1 tablet",
        frequency: "OD",
        route: "ORAL",
        days: 30,
      },
    ],
    advice: "Ultrasound pelvis; review with report.",
    weight: 2,
    gender: "FEMALE",
    ageRange: [30, 50],
  },
  {
    dept: "OBG",
    diagnosis: "Term pregnancy — normal vaginal delivery",
    icd: "O80",
    complaint: "Labour pains at 39 weeks",
    history: "G2P1, regular contractions since morning, membranes intact.",
    exam: "Cervix 4 cm dilated, cephalic presentation, FHS 140/min.",
    labs: ["CBC", "URINE"],
    meds: [],
    advice: "Admit to labour room.",
    weight: 1,
    gender: "FEMALE",
    ageRange: [21, 36],
    inpatient: {
      stay: [2, 3],
      ivMeds: [
        {
          code: "RL500",
          dose: "500 ml",
          frequency: "BD",
          route: "IV",
          days: 1,
        },
        {
          code: "PCM650",
          dose: "1 tablet",
          frequency: "TDS",
          route: "ORAL",
          days: 2,
        },
      ],
      procedure: {
        name: "Normal delivery — labour room & obstetrician charges",
        charge: 22000,
      },
      course:
        "Delivered a healthy male baby weighing 3.1 kg by normal vaginal delivery with right mediolateral episiotomy. Mother and baby stable; breastfeeding established.",
      dischargeMeds: [
        {
          code: "FER100",
          dose: "1 tablet",
          frequency: "OD",
          route: "ORAL",
          days: 30,
        },
        {
          code: "CAD3",
          dose: "1 tablet",
          frequency: "BD",
          route: "ORAL",
          days: 30,
        },
      ],
      diet: "Normal diet, extra fluids",
    },
  },

  // ENT
  {
    dept: "ENT",
    diagnosis: "Acute tonsillitis",
    icd: "J03.9",
    complaint: "Painful swallowing and fever",
    history: "Throat pain for 3 days, fever, no breathing difficulty.",
    exam: "Enlarged congested tonsils with exudate, tender neck nodes.",
    labs: ["CBC"],
    meds: [
      {
        code: "AMC625",
        dose: "1 tablet",
        frequency: "BD",
        route: "ORAL",
        days: 5,
      },
      {
        code: "PCM650",
        dose: "1 tablet",
        frequency: "TDS",
        route: "ORAL",
        days: 3,
      },
    ],
    advice: "Warm saline gargles, soft diet.",
    weight: 4,
  },
  {
    dept: "ENT",
    diagnosis: "Otitis externa",
    icd: "H60.9",
    complaint: "Ear pain and itching",
    history: "Swimming last week, now pain in right ear.",
    exam: "Oedematous external canal, TM intact.",
    labs: [],
    meds: [
      {
        code: "CIPED",
        dose: "3 drops",
        frequency: "TDS",
        route: "TOPICAL",
        days: 7,
      },
      {
        code: "IBU400",
        dose: "1 tablet",
        frequency: "BD",
        route: "ORAL",
        days: 3,
      },
    ],
    advice: "Keep ear dry.",
    weight: 3,
  },
  {
    dept: "ENT",
    diagnosis: "Chronic rhinosinusitis",
    icd: "J32.9",
    complaint: "Blocked nose and headache",
    history: "Nasal block and post-nasal drip for 3 months.",
    exam: "Deviated septum to left, hypertrophied turbinates.",
    labs: [],
    meds: [
      {
        code: "MON10",
        dose: "1 tablet",
        frequency: "HS",
        route: "ORAL",
        days: 14,
      },
      {
        code: "LCZ5",
        dose: "1 tablet",
        frequency: "HS",
        route: "ORAL",
        days: 14,
      },
    ],
    advice: "CT paranasal sinuses advised.",
    weight: 2,
  },

  // Dermatology
  {
    dept: "DER",
    diagnosis: "Tinea corporis",
    icd: "B35.4",
    complaint: "Itchy ring-shaped rash",
    history: "Spreading itchy patches on waist for a month.",
    exam: "Annular scaly plaques with active margins.",
    labs: [],
    meds: [
      {
        code: "CLT15",
        dose: "Apply thin layer",
        frequency: "BD",
        route: "TOPICAL",
        days: 21,
      },
      {
        code: "LCZ5",
        dose: "1 tablet",
        frequency: "HS",
        route: "ORAL",
        days: 10,
      },
    ],
    advice: "Keep area dry, wash clothes separately.",
    weight: 4,
  },
  {
    dept: "DER",
    diagnosis: "Allergic contact dermatitis",
    icd: "L23.9",
    complaint: "Itching and redness on hands",
    history: "Started after using a new detergent.",
    exam: "Erythematous papules on dorsum of both hands.",
    labs: [],
    meds: [
      {
        code: "BTM20",
        dose: "Apply thin layer",
        frequency: "BD",
        route: "TOPICAL",
        days: 7,
      },
      {
        code: "CET10",
        dose: "1 tablet",
        frequency: "HS",
        route: "ORAL",
        days: 7,
      },
    ],
    advice: "Avoid the suspected detergent; use gloves.",
    weight: 3,
  },
  {
    dept: "DER",
    diagnosis: "Impetigo",
    icd: "L01.0",
    complaint: "Crusted sores around the mouth",
    history: "Honey-coloured crusts for 5 days.",
    exam: "Crusted erosions perioral region.",
    labs: [],
    meds: [
      {
        code: "MUP5",
        dose: "Apply",
        frequency: "TDS",
        route: "TOPICAL",
        days: 7,
      },
    ],
    advice: "Keep nails short, avoid sharing towels.",
    weight: 2,
    ageRange: [3, 25],
  },

  // General Surgery
  {
    dept: "SUR",
    diagnosis: "Skin abscess — incision and drainage",
    icd: "L02.9",
    complaint: "Painful swelling on the thigh",
    history: "Swelling for 5 days with fever.",
    exam: "Fluctuant 3 × 3 cm abscess left thigh.",
    labs: ["CBC", "FBS"],
    meds: [
      {
        code: "AMC625",
        dose: "1 tablet",
        frequency: "BD",
        route: "ORAL",
        days: 5,
      },
      {
        code: "IBU400",
        dose: "1 tablet",
        frequency: "TDS",
        route: "ORAL",
        days: 3,
      },
    ],
    advice: "Daily dressing, review in 3 days.",
    weight: 3,
  },
  {
    dept: "SUR",
    diagnosis: "Inguinal hernia",
    icd: "K40.9",
    complaint: "Swelling in the right groin",
    history: "Reducible swelling for 4 months, increases on coughing.",
    exam: "Reducible right inguinal hernia, cough impulse positive.",
    labs: ["CBC"],
    meds: [],
    advice: "Elective hernioplasty advised.",
    weight: 2,
    gender: "MALE",
    ageRange: [30, 75],
  },
  {
    dept: "SUR",
    diagnosis: "Acute appendicitis",
    icd: "K35.8",
    complaint: "Pain in the right lower abdomen with vomiting",
    history: "Periumbilical pain shifting to right iliac fossa over 18 hours.",
    exam: "Tenderness and guarding at McBurney's point, Temp 38 °C.",
    labs: ["CBC", "CRP", "URINE"],
    meds: [],
    advice: "Admit for laparoscopic appendicectomy.",
    weight: 1,
    ageRange: [12, 55],
    inpatient: {
      stay: [2, 4],
      ivMeds: [
        { code: "CTR1G", dose: "1 g", frequency: "BD", route: "IV", days: 3 },
        {
          code: "MTZIV",
          dose: "500 mg",
          frequency: "TDS",
          route: "IV",
          days: 3,
        },
        { code: "PANIV", dose: "40 mg", frequency: "OD", route: "IV", days: 3 },
        {
          code: "RL500",
          dose: "500 ml",
          frequency: "TDS",
          route: "IV",
          days: 1,
        },
      ],
      procedure: {
        name: "Laparoscopic appendicectomy — surgeon, anaesthesia & OT charges",
        charge: 45000,
      },
      course:
        "Underwent laparoscopic appendicectomy on the day of admission; inflamed appendix removed. Started orally on post-operative day 1; wounds healthy.",
      dischargeMeds: [
        {
          code: "CFX200",
          dose: "1 tablet",
          frequency: "BD",
          route: "ORAL",
          days: 5,
        },
        {
          code: "PCM650",
          dose: "1 tablet",
          frequency: "TDS",
          route: "ORAL",
          days: 3,
        },
      ],
      diet: "Liquids day 1, soft diet thereafter",
    },
  },
  {
    dept: "SUR",
    diagnosis: "Symptomatic cholelithiasis",
    icd: "K80.2",
    complaint: "Recurrent upper abdominal pain after fatty meals",
    history: "Episodes of right upper quadrant pain for 6 months.",
    exam: "Mild right hypochondrial tenderness. USG: multiple gallstones.",
    labs: ["CBC", "LFT"],
    meds: [],
    advice: "Admit for laparoscopic cholecystectomy.",
    weight: 1,
    ageRange: [30, 70],
    inpatient: {
      stay: [2, 3],
      ivMeds: [
        { code: "CTR1G", dose: "1 g", frequency: "BD", route: "IV", days: 2 },
        { code: "PANIV", dose: "40 mg", frequency: "OD", route: "IV", days: 2 },
        { code: "ONDIV", dose: "4 mg", frequency: "BD", route: "IV", days: 1 },
      ],
      procedure: {
        name: "Laparoscopic cholecystectomy — surgeon, anaesthesia & OT charges",
        charge: 55000,
      },
      course:
        "Elective laparoscopic cholecystectomy performed on day 1 without complications. Tolerating diet; port sites healthy.",
      dischargeMeds: [
        {
          code: "PCM650",
          dose: "1 tablet",
          frequency: "TDS",
          route: "ORAL",
          days: 5,
        },
        {
          code: "PAN40",
          dose: "1 tablet",
          frequency: "OD",
          route: "ORAL",
          days: 7,
        },
      ],
      diet: "Low fat diet for 4 weeks",
    },
  },
];

/* ------------------------------------------------------------------ */
/* People                                                              */
/* ------------------------------------------------------------------ */

export const FIRST_NAMES_MALE = [
  "Aarav",
  "Vihaan",
  "Aditya",
  "Rohit",
  "Sanjay",
  "Mahesh",
  "Ramesh",
  "Nitin",
  "Abhishek",
  "Kunal",
  "Omkar",
  "Tushar",
  "Yash",
  "Sachin",
  "Vinod",
  "Ajay",
  "Mohit",
  "Sagar",
  "Pranav",
  "Harsh",
  "Anil",
  "Dinesh",
  "Ravi",
  "Akash",
  "Ishaan",
  "Kabir",
  "Vivek",
  "Chetan",
  "Rajesh",
  "Mukesh",
  "Atharv",
  "Reyansh",
  "Shaurya",
  "Ayaan",
  "Farhan",
  "Joseph",
  "Gurpreet",
  "Aniket",
  "Swapnil",
  "Hemant",
];

export const FIRST_NAMES_FEMALE = [
  "Aanya",
  "Diya",
  "Saanvi",
  "Priyanka",
  "Kavita",
  "Sunita",
  "Rekha",
  "Shweta",
  "Pallavi",
  "Asmita",
  "Rutuja",
  "Snehal",
  "Madhuri",
  "Vaishali",
  "Anjali",
  "Ishita",
  "Neha",
  "Sonal",
  "Tanvi",
  "Gauri",
  "Shraddha",
  "Komal",
  "Manisha",
  "Jyoti",
  "Radhika",
  "Aditi",
  "Myra",
  "Anika",
  "Zoya",
  "Grace",
  "Harpreet",
  "Nisha",
  "Rashmi",
  "Yamini",
  "Varsha",
  "Swara",
  "Kiara",
  "Meenal",
  "Shital",
  "Archana",
];

export const LAST_NAMES = [
  "Patil",
  "Deshmukh",
  "Kulkarni",
  "Joshi",
  "Pawar",
  "Jadhav",
  "Shinde",
  "Gaikwad",
  "Chavan",
  "Kale",
  "Sharma",
  "Verma",
  "Gupta",
  "Singh",
  "Yadav",
  "Mishra",
  "Iyer",
  "Reddy",
  "Naidu",
  "Menon",
  "Fernandes",
  "D'Mello",
  "Sheikh",
  "Ansari",
  "Bhatia",
  "Malhotra",
  "Kapoor",
  "Agarwal",
  "Jain",
  "Shah",
  "Mehta",
  "Desai",
  "Thakur",
  "Rathod",
  "Sawant",
  "More",
  "Bhosale",
  "Nikam",
  "Salunkhe",
  "Wagh",
];

export const LOCALITIES = [
  "Baner",
  "Aundh",
  "Pashan",
  "Kothrud",
  "Wakad",
  "Hinjewadi",
  "Pimple Saudagar",
  "Balewadi",
  "Shivajinagar",
  "Deccan",
  "Karve Nagar",
  "Warje",
  "Bavdhan",
  "Sus",
  "Viman Nagar",
  "Kharadi",
];

export const ALLERGIES = [
  "Penicillin",
  "Sulfa drugs",
  "NSAID",
  "Peanuts",
  "Latex",
  "Iodine contrast",
  "Dust mites",
];

export const CHRONIC = [
  "Type 2 diabetes",
  "Hypertension",
  "Hypothyroidism",
  "Asthma",
  "Dyslipidaemia",
  "Chronic kidney disease",
];
